path: /content/drive/MyDrive/YOLOV8/data
train: images/train
val: images/train
#test: images/test

# Classes
nc: 8  # Number of classes (total number of unique classes)
names: ['cottonoid', 'drill', 'grasper', 'muscle', 'scalpel', 'string', 'suction', 'tool']